# Generated by Django 4.2.1 on 2023-05-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articlepost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
        migrations.DeleteModel(
            name='ArticleColumn',
        ),
    ]
